name: Deploy ML Model

on:
  workflow_dispatch:

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: us-west-2
      BUCKET_NAME: your-bucket-name

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install joblib scikit-learn boto3

    - name: Train and save model
      run: |
        python ml_prediction/iris_model.py
        mv iris_model.joblib ml_deployment/

    - name: Package Lambda function
      run: |
        cd ml_deployment
        zip -r lambda_function_payload.zip lambda_function.py iris_model.joblib

    - name: Install Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Terraform Init
      run: terraform init
      working-directory: iac

    - name: Terraform Apply
      run: terraform apply -auto-approve
      working-directory: iac
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

